# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_setting.ui'
#
# Created: Sun Jul  8 23:54:29 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dlg_setting(object):
    def setupUi(self, Dlg_setting):
        Dlg_setting.setObjectName(_fromUtf8("Dlg_setting"))
        Dlg_setting.resize(221, 481)
        Dlg_setting.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.groupBox_2 = QtGui.QGroupBox(Dlg_setting)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 221, 481))
        self.groupBox_2.setStyleSheet(_fromUtf8("QGroupBox {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #E0E0E0, stop: 1 #FFFFFF);\n"
"     border: 2px solid gray;\n"
"     border-radius: 5px;\n"
"     margin-top: 1ex; /* leave space at the top for the title */\n"
" }\n"
"QGroupBox::title {\n"
"     subcontrol-origin: margin;\n"
"     subcontrol-position: top center; /* position at the top center */\n"
"     padding: 0 3px;\n"
" }"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.line_split_2 = QtGui.QFrame(self.groupBox_2)
        self.line_split_2.setGeometry(QtCore.QRect(20, 190, 181, 16))
        self.line_split_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_split_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_split_2.setObjectName(_fromUtf8("line_split_2"))
        self.doubleSpinBox_cache = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_cache.setGeometry(QtCore.QRect(70, 160, 111, 25))
        self.doubleSpinBox_cache.setMaximum(999999999.99)
        self.doubleSpinBox_cache.setObjectName(_fromUtf8("doubleSpinBox_cache"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(180, 160, 16, 25))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(15, 160, 52, 25))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_setting_title = QtGui.QLabel(self.groupBox_2)
        self.label_setting_title.setGeometry(QtCore.QRect(70, 200, 91, 20))
        self.label_setting_title.setObjectName(_fromUtf8("label_setting_title"))
        self.label_login = QtGui.QLabel(self.groupBox_2)
        self.label_login.setGeometry(QtCore.QRect(50, 225, 31, 16))
        self.label_login.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_login.setObjectName(_fromUtf8("label_login"))
        self.lineEdit_login = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_login.setGeometry(QtCore.QRect(85, 220, 91, 25))
        self.lineEdit_login.setObjectName(_fromUtf8("lineEdit_login"))
        self.lineEdit_quit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_quit.setGeometry(QtCore.QRect(85, 250, 91, 25))
        self.lineEdit_quit.setObjectName(_fromUtf8("lineEdit_quit"))
        self.label_quit = QtGui.QLabel(self.groupBox_2)
        self.label_quit.setGeometry(QtCore.QRect(50, 250, 31, 20))
        self.label_quit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_quit.setObjectName(_fromUtf8("label_quit"))
        self.lineEdit_next = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_next.setGeometry(QtCore.QRect(85, 310, 91, 25))
        self.lineEdit_next.setObjectName(_fromUtf8("lineEdit_next"))
        self.lineEdit_play_pause = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_play_pause.setGeometry(QtCore.QRect(85, 280, 91, 25))
        self.lineEdit_play_pause.setObjectName(_fromUtf8("lineEdit_play_pause"))
        self.label_next = QtGui.QLabel(self.groupBox_2)
        self.label_next.setGeometry(QtCore.QRect(40, 315, 41, 20))
        self.label_next.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_next.setObjectName(_fromUtf8("label_next"))
        self.label_play_pause = QtGui.QLabel(self.groupBox_2)
        self.label_play_pause.setGeometry(QtCore.QRect(20, 280, 61, 20))
        self.label_play_pause.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_play_pause.setObjectName(_fromUtf8("label_play_pause"))
        self.lineEdit_ban = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_ban.setGeometry(QtCore.QRect(85, 375, 91, 25))
        self.lineEdit_ban.setObjectName(_fromUtf8("lineEdit_ban"))
        self.label_ban = QtGui.QLabel(self.groupBox_2)
        self.label_ban.setGeometry(QtCore.QRect(30, 380, 51, 16))
        self.label_ban.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ban.setObjectName(_fromUtf8("label_ban"))
        self.label_like = QtGui.QLabel(self.groupBox_2)
        self.label_like.setGeometry(QtCore.QRect(10, 350, 71, 16))
        self.label_like.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_like.setObjectName(_fromUtf8("label_like"))
        self.lineEdit_like = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_like.setGeometry(QtCore.QRect(85, 340, 91, 25))
        self.lineEdit_like.setObjectName(_fromUtf8("lineEdit_like"))
        self.line_split_1 = QtGui.QFrame(self.groupBox_2)
        self.line_split_1.setGeometry(QtCore.QRect(20, 130, 191, 20))
        self.line_split_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_split_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_split_1.setObjectName(_fromUtf8("line_split_1"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 163, 27))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_password = QtGui.QLabel(self.layoutWidget)
        self.label_password.setObjectName(_fromUtf8("label_password"))
        self.horizontalLayout_3.addWidget(self.label_password)
        self.lineEdit_password = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_password.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_password.setObjectName(_fromUtf8("lineEdit_password"))
        self.horizontalLayout_3.addWidget(self.lineEdit_password)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 40, 163, 27))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_username = QtGui.QLabel(self.layoutWidget1)
        self.label_username.setObjectName(_fromUtf8("label_username"))
        self.horizontalLayout_2.addWidget(self.label_username)
        self.lineEdit_username = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_username.setObjectName(_fromUtf8("lineEdit_username"))
        self.horizontalLayout_2.addWidget(self.lineEdit_username)
        self.checkBox_remember = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_remember.setGeometry(QtCore.QRect(30, 110, 91, 20))
        self.checkBox_remember.setObjectName(_fromUtf8("checkBox_remember"))
        self.label_setting_title_2 = QtGui.QLabel(self.groupBox_2)
        self.label_setting_title_2.setGeometry(QtCore.QRect(80, 20, 81, 20))
        self.label_setting_title_2.setObjectName(_fromUtf8("label_setting_title_2"))
        self.label_setting_title_3 = QtGui.QLabel(self.groupBox_2)
        self.label_setting_title_3.setGeometry(QtCore.QRect(70, 140, 91, 20))
        self.label_setting_title_3.setObjectName(_fromUtf8("label_setting_title_3"))
        self.pushButton_cancle = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_cancle.setGeometry(QtCore.QRect(150, 450, 65, 27))
        self.pushButton_cancle.setObjectName(_fromUtf8("pushButton_cancle"))
        self.pushButton_reset = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_reset.setGeometry(QtCore.QRect(80, 450, 65, 27))
        self.pushButton_reset.setObjectName(_fromUtf8("pushButton_reset"))
        self.pushButton_set = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_set.setGeometry(QtCore.QRect(10, 450, 65, 27))
        self.pushButton_set.setObjectName(_fromUtf8("pushButton_set"))
        self.line_split_3 = QtGui.QFrame(self.groupBox_2)
        self.line_split_3.setGeometry(QtCore.QRect(20, 430, 191, 20))
        self.line_split_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_split_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_split_3.setObjectName(_fromUtf8("line_split_3"))
        self.lineEdit_setting = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_setting.setGeometry(QtCore.QRect(85, 405, 91, 25))
        self.lineEdit_setting.setObjectName(_fromUtf8("lineEdit_setting"))
        self.label_setting = QtGui.QLabel(self.groupBox_2)
        self.label_setting.setGeometry(QtCore.QRect(50, 410, 31, 20))
        self.label_setting.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_setting.setObjectName(_fromUtf8("label_setting"))

        self.retranslateUi(Dlg_setting)
        QtCore.QMetaObject.connectSlotsByName(Dlg_setting)
        Dlg_setting.setTabOrder(self.lineEdit_username, self.lineEdit_password)
        Dlg_setting.setTabOrder(self.lineEdit_password, self.checkBox_remember)
        Dlg_setting.setTabOrder(self.checkBox_remember, self.doubleSpinBox_cache)
        Dlg_setting.setTabOrder(self.doubleSpinBox_cache, self.lineEdit_login)
        Dlg_setting.setTabOrder(self.lineEdit_login, self.lineEdit_quit)
        Dlg_setting.setTabOrder(self.lineEdit_quit, self.lineEdit_play_pause)
        Dlg_setting.setTabOrder(self.lineEdit_play_pause, self.lineEdit_next)
        Dlg_setting.setTabOrder(self.lineEdit_next, self.lineEdit_like)
        Dlg_setting.setTabOrder(self.lineEdit_like, self.lineEdit_ban)
        Dlg_setting.setTabOrder(self.lineEdit_ban, self.lineEdit_setting)
        Dlg_setting.setTabOrder(self.lineEdit_setting, self.pushButton_set)
        Dlg_setting.setTabOrder(self.pushButton_set, self.pushButton_reset)
        Dlg_setting.setTabOrder(self.pushButton_reset, self.pushButton_cancle)

    def retranslateUi(self, Dlg_setting):
        Dlg_setting.setWindowTitle(QtGui.QApplication.translate("Dlg_setting", "设置", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dlg_setting", "设置", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_cache.setToolTip(QtGui.QApplication.translate("Dlg_setting", "<html><head/><body><p>0表示不限制,单位为M</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_cache.setWhatsThis(QtGui.QApplication.translate("Dlg_setting", "<html><head/><body><p>0表示不限制,单位M</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dlg_setting", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dlg_setting", "缓存大小", None, QtGui.QApplication.UnicodeUTF8))
        self.label_setting_title.setText(QtGui.QApplication.translate("Dlg_setting", "--快捷键设置--", None, QtGui.QApplication.UnicodeUTF8))
        self.label_login.setText(QtGui.QApplication.translate("Dlg_setting", "登录", None, QtGui.QApplication.UnicodeUTF8))
        self.label_quit.setText(QtGui.QApplication.translate("Dlg_setting", "退出", None, QtGui.QApplication.UnicodeUTF8))
        self.label_next.setText(QtGui.QApplication.translate("Dlg_setting", "下一首", None, QtGui.QApplication.UnicodeUTF8))
        self.label_play_pause.setText(QtGui.QApplication.translate("Dlg_setting", "播放/暂停", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ban.setText(QtGui.QApplication.translate("Dlg_setting", "不再收听", None, QtGui.QApplication.UnicodeUTF8))
        self.label_like.setText(QtGui.QApplication.translate("Dlg_setting", "加红/不加红", None, QtGui.QApplication.UnicodeUTF8))
        self.label_password.setText(QtGui.QApplication.translate("Dlg_setting", "密码", None, QtGui.QApplication.UnicodeUTF8))
        self.label_username.setText(QtGui.QApplication.translate("Dlg_setting", "帐号", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_remember.setToolTip(QtGui.QApplication.translate("Dlg_setting", "<html><head/><body><p>为了帐号的安全性，请不要在公用机器上面勾选，虽然密码已经过加密存放</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_remember.setText(QtGui.QApplication.translate("Dlg_setting", "记住密码", None, QtGui.QApplication.UnicodeUTF8))
        self.label_setting_title_2.setText(QtGui.QApplication.translate("Dlg_setting", "--豆瓣信息--", None, QtGui.QApplication.UnicodeUTF8))
        self.label_setting_title_3.setText(QtGui.QApplication.translate("Dlg_setting", "--客户端设置--", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cancle.setText(QtGui.QApplication.translate("Dlg_setting", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_reset.setText(QtGui.QApplication.translate("Dlg_setting", "重置", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_set.setText(QtGui.QApplication.translate("Dlg_setting", "设置", None, QtGui.QApplication.UnicodeUTF8))
        self.label_setting.setText(QtGui.QApplication.translate("Dlg_setting", "设置", None, QtGui.QApplication.UnicodeUTF8))

